export { default as Home} from './home'
export { default as AboutMe} from './aboutme'
export { default as ContactMe} from './contactme'
export { default as Projects} from './projects'
export { default as Resume} from './resume'
export { default as Sidebar} from './sidebar'